/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnimatedAreaChart {
        "chartTitle"?: string;
        /**
          * @default '#3b82f6'
         */
        "color": string;
        /**
          * @default []
         */
        "data": number[];
        /**
          * @default 240
         */
        "height": number;
        /**
          * @default []
         */
        "labels": string[];
    }
    interface AnimatedBarChart {
        "chartTitle"?: string;
        /**
          * @default []
         */
        "colors": string[];
        /**
          * @default []
         */
        "data": number[];
        /**
          * @default 240
         */
        "height": number;
        /**
          * @default []
         */
        "labels": string[];
    }
    interface AnimatedDonutChart {
        "chartTitle"?: string;
        /**
          * @default []
         */
        "colors": string[];
        /**
          * @default []
         */
        "data": number[];
        /**
          * @default []
         */
        "labels": string[];
        /**
          * @default 120
         */
        "size": number;
        /**
          * @default 16
         */
        "strokeWidth": number;
    }
    interface AnimatedLineChart {
        "chartTitle"?: string;
        /**
          * @default '#3b82f6'
         */
        "color": string;
        /**
          * @default []
         */
        "data": number[];
        /**
          * @default 240
         */
        "height": number;
        /**
          * @default []
         */
        "labels": string[];
    }
}
declare global {
    interface HTMLAnimatedAreaChartElement extends Components.AnimatedAreaChart, HTMLStencilElement {
    }
    var HTMLAnimatedAreaChartElement: {
        prototype: HTMLAnimatedAreaChartElement;
        new (): HTMLAnimatedAreaChartElement;
    };
    interface HTMLAnimatedBarChartElement extends Components.AnimatedBarChart, HTMLStencilElement {
    }
    var HTMLAnimatedBarChartElement: {
        prototype: HTMLAnimatedBarChartElement;
        new (): HTMLAnimatedBarChartElement;
    };
    interface HTMLAnimatedDonutChartElement extends Components.AnimatedDonutChart, HTMLStencilElement {
    }
    var HTMLAnimatedDonutChartElement: {
        prototype: HTMLAnimatedDonutChartElement;
        new (): HTMLAnimatedDonutChartElement;
    };
    interface HTMLAnimatedLineChartElement extends Components.AnimatedLineChart, HTMLStencilElement {
    }
    var HTMLAnimatedLineChartElement: {
        prototype: HTMLAnimatedLineChartElement;
        new (): HTMLAnimatedLineChartElement;
    };
    interface HTMLElementTagNameMap {
        "animated-area-chart": HTMLAnimatedAreaChartElement;
        "animated-bar-chart": HTMLAnimatedBarChartElement;
        "animated-donut-chart": HTMLAnimatedDonutChartElement;
        "animated-line-chart": HTMLAnimatedLineChartElement;
    }
}
declare namespace LocalJSX {
    interface AnimatedAreaChart {
        "chartTitle"?: string;
        /**
          * @default '#3b82f6'
         */
        "color"?: string;
        /**
          * @default []
         */
        "data"?: number[];
        /**
          * @default 240
         */
        "height"?: number;
        /**
          * @default []
         */
        "labels"?: string[];
    }
    interface AnimatedBarChart {
        "chartTitle"?: string;
        /**
          * @default []
         */
        "colors"?: string[];
        /**
          * @default []
         */
        "data"?: number[];
        /**
          * @default 240
         */
        "height"?: number;
        /**
          * @default []
         */
        "labels"?: string[];
    }
    interface AnimatedDonutChart {
        "chartTitle"?: string;
        /**
          * @default []
         */
        "colors"?: string[];
        /**
          * @default []
         */
        "data"?: number[];
        /**
          * @default []
         */
        "labels"?: string[];
        /**
          * @default 120
         */
        "size"?: number;
        /**
          * @default 16
         */
        "strokeWidth"?: number;
    }
    interface AnimatedLineChart {
        "chartTitle"?: string;
        /**
          * @default '#3b82f6'
         */
        "color"?: string;
        /**
          * @default []
         */
        "data"?: number[];
        /**
          * @default 240
         */
        "height"?: number;
        /**
          * @default []
         */
        "labels"?: string[];
    }
    interface IntrinsicElements {
        "animated-area-chart": AnimatedAreaChart;
        "animated-bar-chart": AnimatedBarChart;
        "animated-donut-chart": AnimatedDonutChart;
        "animated-line-chart": AnimatedLineChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animated-area-chart": LocalJSX.AnimatedAreaChart & JSXBase.HTMLAttributes<HTMLAnimatedAreaChartElement>;
            "animated-bar-chart": LocalJSX.AnimatedBarChart & JSXBase.HTMLAttributes<HTMLAnimatedBarChartElement>;
            "animated-donut-chart": LocalJSX.AnimatedDonutChart & JSXBase.HTMLAttributes<HTMLAnimatedDonutChartElement>;
            "animated-line-chart": LocalJSX.AnimatedLineChart & JSXBase.HTMLAttributes<HTMLAnimatedLineChartElement>;
        }
    }
}
